# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

username: <%= Figaro.env.username %>
password: <%= Figaro.env.password %>

development:
  secret_key_base: d6824a0d623797d83482a2aa2be2433868248bdbacb8c340e2efa3d994903d91d93af8e45902b920628ac76538c7d6d459632ef9c4d41a7508af8a0ffd67a274

test:
  secret_key_base: 1f769c8502603cac4aa6809c1c437a55b108b927ec592ad5afced17e76c22b456d8d8283676a43823f073ea7b6062f79336b10ad1f69f7e8a5c137b6cc9ba43f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
